repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-toml
    -   id: check-yaml
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
    -   id: trailing-whitespace
-   repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 2.4.0
    hooks:
    -   id: editorconfig-checker
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
-   repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
    -   id: isort
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
        additional_dependencies:
        -   flake8-bandit==3.0.0
        -   flake8-bugbear==22.4.25
        -   flake8-builtins==1.5.3
        -   flake8-comprehensions==3.8.0
        -   flake8-docstrings==1.6.0
        -   flake8-pytest-style==1.6.0
        -   pep8-naming==0.12.1
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.950
    hooks:
    -   id: mypy
        args: []
        additional_dependencies:
        -   numpy==1.22.3
        -   pytest==7.1.2
-   repo: https://github.com/nbQA-dev/nbQA
    rev: 1.3.1
    hooks:
    -   id: nbqa-black
        additional_dependencies:
        -   black==22.3.0
    -   id: nbqa-isort
        additional_dependencies:
        -   isort==5.10.1
    -   id: nbqa-mypy
        additional_dependencies:
        -   mypy==0.950
        -   numpy==1.22.3
        -   pytest==7.1.2
-   repo: https://github.com/jorisroovers/gitlint
    rev: v0.17.0
    hooks:
    -   id: gitlint
