default_install_hook_types: [pre-commit, commit-msg]

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-executables-have-shebangs
    -   id: check-merge-conflict
    -   id: check-shebang-scripts-are-executable
    -   id: check-symlinks
    -   id: check-toml
    -   id: check-yaml
    -   id: destroyed-symlinks
    -   id: end-of-file-fixer
    -   id: fix-byte-order-marker
    -   id: mixed-line-ending
    -   id: trailing-whitespace

-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black

-   repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
    -   id: isort

-   repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 2.6.1
    hooks:
    -   id: editorconfig-checker

-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        entry: pflake8
        additional_dependencies:
        -   flake8-bandit==4.1.1
        -   flake8-bugbear==22.10.27
        -   flake8-builtins==2.0.1
        -   flake8-comprehensions==3.10.1
        -   flake8-docstrings==1.6.0
        -   flake8-pytest-style==1.6.0
        -   pep8-naming==0.13.2
        -   pyproject-flake8==5.0.4a1.post1

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
    -   id: mypy
        args: []
        additional_dependencies:
        -   numpy==1.23.5
        -   pytest==7.2.0

-   repo: https://github.com/nbQA-dev/nbQA
    rev: 1.5.3
    hooks:
    -   id: nbqa-black
        additional_dependencies:
        -   black==22.10.0
    -   id: nbqa-isort
        additional_dependencies:
        -   isort==5.10.1
    -   id: nbqa-mypy
        args: [
            --allow-untyped-call,
            --allow-untyped-defs
        ]
        additional_dependencies:
        -   mypy==0.991
        -   numpy==1.23.5
        -   pytest==7.2.0

-   repo: https://github.com/jorisroovers/gitlint
    rev: v0.18.0
    hooks:
    -   id: gitlint
