repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-toml
    -   id: check-yaml
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
    -   id: trailing-whitespace
-   repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 2.3.54
    hooks:
    -   id: editorconfig-checker
-   repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
    -   id: black
-   repo: https://github.com/timothycrosley/isort
    rev: 5.9.3
    hooks:
    -   id: isort
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
        additional_dependencies:
        -   flake8-bandit==2.1.2
        -   flake8-bugbear==21.9.2
        -   flake8-builtins==1.5.3
        -   flake8-comprehensions==3.7.0
        -   flake8-docstrings==1.6.0
        -   flake8-pytest-style==1.5.0
        -   pep8-naming==0.12.1
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910-1
    hooks:
    -   id: mypy
        args: []
        additional_dependencies:
        -   numpy==1.21.3
        -   pytest==6.2.5
-   repo: https://github.com/nbQA-dev/nbQA
    rev: 1.1.1
    hooks:
    -   id: nbqa-black
        additional_dependencies:
        -   black==21.9b0
    -   id: nbqa-isort
        additional_dependencies:
        -   isort==5.9.3
    -   id: nbqa-mypy
        additional_dependencies:
        -   mypy==0.910
        -   numpy==1.21.3
        -   pytest==6.2.5
-   repo: https://github.com/jorisroovers/gitlint
    rev: v0.16.0
    hooks:
    -   id: gitlint
